export const KEYBOARD_STRUCTURE = [
  [ // row1
    {val: ['`', 'ё']},
    {val: ['1']},
    {val: ['2']},
    {val: ['3']},
    {val: ['4']},
    {val: ['5']},
    {val: ['6']},
    {val: ['7']},
    {val: ['8']},
    {val: ['9']},
    {val: ['-']},
    {val: ['=']},
    {val: ['Backspace'], grow: 1},
  ],
  [ // row2
    {val: ['Tab']},
    {val: ['q', 'й']},
    {val: ['w', 'ц']},
    {val: ['e', 'у']},
    {val: ['r', 'к']},
    {val: ['t', 'е']},
    {val: ['y', 'н']},
    {val: ['u', 'г']},
    {val: ['i', 'ш']},
    {val: ['o', 'щ']},
    {val: ['p', 'з']},
    {val: ['[', 'х']},
    {val: [']', 'ъ']},
    {val: ['\\']},
    {val: ['Del', 'ё']},
  ],
  [ // row 3
    {val: ['CapsLock'], grow: 1},
    {val: ['a', 'ф']},
    {val: ['s', 'ы']},
    {val: ['d', 'в']},
    {val: ['f', 'а']},
    {val: ['g', 'п']},
    {val: ['h', 'р']},
    {val: ['j', 'о']},
    {val: ['k', 'л']},
    {val: ['l', 'д']},
    {val: [';', 'ж']},
    {val: ['\'', 'э']},
    {val: ['Enter'], grow: 1},
  ],
  [ // row 4
    {val: ['Shift'], grow: 1},
    {val: ['z', 'я']},
    {val: ['x', 'ч']},
    {val: ['c', 'с']},
    {val: ['v', 'м']},
    {val: ['b', 'и']},
    {val: ['n', 'т']},
    {val: ['m', 'ь']},
    {val: [',', 'б']},
    {val: ['.', 'ю']},
    {val: ['/', '.']},
    {val: ['▲']},
    {val: ['Shift'], grow: 0.75},
  ],
  [ // row 5
    {val: ['Ctrl']},
    {val: ['Win']},
    {val: ['Alt']},
    {val: [' '], grow: 1},
    {val: ['Alt']},
    {val: ['◄']},
    {val: ['▼']},
    {val: ['►']},
    {val: ['Ctrl']},
  ],
];

