export const KEYBOARD_STRUCTURE = [
  [ // row1
    {val: ['`', 'ё'], code: 'Backquote'},
    {val: ['1'], code: 'Digit1'},
    {val: ['2'], code: 'Digit2'},
    {val: ['3'], code: 'Digit3'},
    {val: ['4'], code: 'Digit4'},
    {val: ['5'], code: 'Digit5'},
    {val: ['6'], code: 'Digit6'},
    {val: ['7'], code: 'Digit7'},
    {val: ['8'], code: 'Digit8'},
    {val: ['9'], code: 'Digit9'},
    {val: ['-'], code: 'Minus'},
    {val: ['='], code: 'Equal'},
    {val: ['Backspace'], code: 'Backspace', grow: 1},
  ],
  [ // row2
    {val: ['Tab'], code: 'Tab'},
    {val: ['q', 'й'], code: 'KeyQ'},
    {val: ['w', 'ц'], code: 'KeyW'},
    {val: ['e', 'у'], code: 'KeyE'},
    {val: ['r', 'к'], code: 'KeyR'},
    {val: ['t', 'е'], code: 'KeyT'},
    {val: ['y', 'н'], code: 'KeyY'},
    {val: ['u', 'г'], code: 'KeyU'},
    {val: ['i', 'ш'], code: 'KeyI'},
    {val: ['o', 'щ'], code: 'KeyO'},
    {val: ['p', 'з'], code: 'KeyP'},
    {val: ['[', 'х'], code: 'BracketLeft'},
    {val: [']', 'ъ'], code: 'BracketRight'},
    {val: ['\\'], code: 'Backslash'},
    {val: ['Del', 'ё'], code: 'Delete'},
  ],
  [ // row 3
    {val: ['CapsLock'], code: 'CapsLock', grow: 1},
    {val: ['a', 'ф'], code: 'KeyA'},
    {val: ['s', 'ы'], code: 'KeyS'},
    {val: ['d', 'в'], code: 'KeyD'},
    {val: ['f', 'а'], code: 'KeyF'},
    {val: ['g', 'п'], code: 'KeyG'},
    {val: ['h', 'р'], code: 'KeyH'},
    {val: ['j', 'о'], code: 'KeyJ'},
    {val: ['k', 'л'], code: 'KeyK'},
    {val: ['l', 'д'], code: 'KeyL'},
    {val: [';', 'ж'], code: 'Semicolon'},
    {val: ['\'', 'э'], code: 'Quote'},
    {val: ['Enter'], code: 'Enter', grow: 1},
  ],
  [ // row 4
    {val: ['Shift'], code: 'ShiftLeft', grow: 1},
    {val: ['z', 'я'], code: 'KeyZ'},
    {val: ['x', 'ч'], code: 'KeyX'},
    {val: ['v', 'м'], code: 'KeyC'},
    {val: ['c', 'с'], code: 'KeyV'},
    {val: ['b', 'и'], code: 'KeyB'},
    {val: ['n', 'т'], code: 'KeyN'},
    {val: ['m', 'ь'], code: 'KeyM'},
    {val: [',', 'б'], code: 'Comma'},
    {val: ['.', 'ю'], code: 'Period'},
    {val: ['/', '.'], code: 'Slash'},
    {val: ['▲'], code: 'ArrowUp'},
    {val: ['Shift'], code: 'ShiftRight', grow: 0.75},
  ],
  [ // row 5
    {val: ['Ctrl'], code: 'ControlLeft'},
    {val: ['Win'], code: 'MetaLeft'},
    {val: ['Alt'], code: 'AltLeft'},
    {val: [' '], code: 'Space', grow: 1},
    {val: ['Alt'], code: 'AltRight'},
    {val: ['◄'], code: 'ArrowLeft'},
    {val: ['▼'], code: 'ArrowDown'},
    {val: ['►'], code: 'ArrowRight'},
    {val: ['Ctrl'], code: 'ControlRight'},
  ],
];

