export const KEYBOARD_STRUCTURE = [
  [ // row1
    {code: 'Backquote', languageSensitive: true, shiftSensitive: true},
    {code: 'Digit1', languageSensitive: true, shiftSensitive: true},
    {code: 'Digit2', languageSensitive: true, shiftSensitive: true},
    {code: 'Digit3', languageSensitive: true, shiftSensitive: true},
    {code: 'Digit4', languageSensitive: true, shiftSensitive: true},
    {code: 'Digit5', languageSensitive: true, shiftSensitive: true},
    {code: 'Digit6', languageSensitive: true, shiftSensitive: true},
    {code: 'Digit7', languageSensitive: true, shiftSensitive: true},
    {code: 'Digit8', languageSensitive: true, shiftSensitive: true},
    {code: 'Digit9', languageSensitive: true, shiftSensitive: true},
    {code: 'Digit0', languageSensitive: true, shiftSensitive: true},
    {code: 'Minus', languageSensitive: true, shiftSensitive: true},
    {code: 'Equal', languageSensitive: true, shiftSensitive: true},
    {code: 'Backspace', grow: 1},
  ],
  [ // row2
    {code: 'Tab'},
    {code: 'KeyQ', languageSensitive: true},
    {code: 'KeyW', languageSensitive: true},
    {code: 'KeyE', languageSensitive: true},
    {code: 'KeyR', languageSensitive: true},
    {code: 'KeyT', languageSensitive: true},
    {code: 'KeyY', languageSensitive: true},
    {code: 'KeyU', languageSensitive: true},
    {code: 'KeyI', languageSensitive: true},
    {code: 'KeyO', languageSensitive: true},
    {code: 'KeyP', languageSensitive: true},
    {code: 'BracketLeft', languageSensitive: true, shiftSensitive: true},
    {code: 'BracketRight', languageSensitive: true, shiftSensitive: true},
    {code: 'Backslash', shiftSensitive: true},
    {code: 'Delete'},
  ],
  [ // row 3
    {code: 'CapsLock', grow: 1},
    {code: 'KeyA', languageSensitive: true},
    {code: 'KeyS', languageSensitive: true},
    {code: 'KeyD', languageSensitive: true},
    {code: 'KeyF', languageSensitive: true},
    {code: 'KeyG', languageSensitive: true},
    {code: 'KeyH', languageSensitive: true},
    {code: 'KeyJ', languageSensitive: true},
    {code: 'KeyK', languageSensitive: true},
    {code: 'KeyL', languageSensitive: true},
    {code: 'Semicolon', languageSensitive: true, shiftSensitive: true},
    {code: 'Quote', languageSensitive: true, shiftSensitive: true},
    {code: 'Enter', grow: 1},
  ],
  [ // row 4
    {code: 'ShiftLeft', grow: 1},
    {code: 'KeyZ', languageSensitive: true},
    {code: 'KeyX', languageSensitive: true},
    {code: 'KeyC', languageSensitive: true},
    {code: 'KeyV', languageSensitive: true},
    {code: 'KeyB', languageSensitive: true},
    {code: 'KeyN', languageSensitive: true},
    {code: 'KeyM', languageSensitive: true},
    {code: 'Comma', languageSensitive: true, shiftSensitive: true},
    {code: 'Period', languageSensitive: true, shiftSensitive: true},
    {code: 'Slash', languageSensitive: true, shiftSensitive: true},
    {code: 'ArrowUp'},
    {code: 'ShiftRight', grow: 0.9},
  ],
  [ // row 5
    {code: 'ControlLeft'},
    {code: 'MetaLeft'},
    {code: 'AltLeft'},
    {code: 'Space', grow: 1},
    {code: 'AltRight'},
    {code: 'ArrowLeft'},
    {code: 'ArrowDown'},
    {code: 'ArrowRight'},
    {code: 'ControlRight'},
  ],
];


export const KEY_MAP = {
  'ControlRight': {
    'displayValue': 'Ctrl',
    'code': 'ControlRight',
  },
  'ArrowRight': {
    'displayValue': '►',
    'code': 'ArrowRight',
  },
  'ArrowDown': {
    'displayValue': '▼',
    'code': 'ArrowDown',
  },
  'ArrowLeft': {
    'displayValue': '◄',
    'code': 'ArrowLeft',
  },
  'AltRight': {
    'displayValue': 'Alt',
    'code': 'AltRight',
  },
  'Space': {
    'displayValue': ' ',
    'which': 32,
    'code': 'Space',
  },
  'AltLeft': {
    'displayValue': 'Alt',
    'code': 'AltLeft',
  },
  'MetaLeft': {
    'displayValue': 'Win',
    'code': 'MetaLeft',
  },
  'ControlLeft': {
    'displayValue': 'Ctrl',
    'code': 'ControlLeft',
  },
  'ShiftRight': {
    'displayValue': 'Shift',
    'code': 'ShiftRight',
  },
  'ArrowUp': {
    'displayValue': '▲',
    'code': 'ArrowUp',
  },
  'Slash': {
    'displayValue': '/',
    'which': 47,
    'shiftWhich': 63,
    'altWhich': 46,
    'code': 'Slash',
  },
  'Period': {
    'key': '.',
    'which': 46,
    'shiftWhich': 62,
    'altWhich': 1102,
    'code': 'Period',
  },
  'Comma': {
    'key': ',',
    'which': 44,
    'shiftWhich': 60,
    'altWhich': 1073,
    'code': 'Comma',
  },
  'KeyM': {
    'key': 'm',
    'which': 109,
    'altWhich': 1100,
    'code': 'KeyM',
  },
  'KeyN': {
    'key': 'n',
    'which': 110,
    'altWhich': 1090,
    'code': 'KeyN',
  },
  'KeyB': {
    'key': 'b',
    'which': 98,
    'altWhich': 1080,
    'code': 'KeyB',
  },
  'KeyV': {
    'key': 'v',
    'which': 118,
    'altWhich': 1084,
    'code': 'KeyV',
  },
  'KeyC': {
    'key': 'c',
    'which': 99,
    'altWhich': 1089,
    'code': 'KeyC',
  },
  'KeyX': {
    'key': 'x',
    'which': 120,
    'altWhich': 1095,
    'code': 'KeyX',
  },
  'KeyZ': {
    'key': 'z',
    'which': 122,
    'altWhich': 1103,
    'code': 'KeyZ',
  },
  'ShiftLeft': {
    'displayValue': 'Shift',
    'code': 'ShiftLeft',
  },
  'Enter': {
    'key': 'Enter',
    'code': 'Enter',
  },
  'Quote': {
    'key': '\'',
    'which': 0x27,
    'shiftWhich': 34,
    'altWhich': 1101,
    'code': 'Quote',
  },
  'Semicolon': {
    'key': ';',
    'which': 59,
    'shiftWhich': 58,
    'altWhich': 1078,
    'code': 'Semicolon',
  },
  'KeyL': {
    'key': 'l',
    'which': 108,
    'altWhich': 1076,
    'code': 'KeyL',
  },
  'KeyK': {
    'key': 'k',
    'which': 107,
    'altWhich': 1083,
    'code': 'KeyK',
  },
  'KeyJ': {
    'key': 'j',
    'which': 106,
    'altWhich': 1086,
    'code': 'KeyJ',
  },
  'KeyH': {
    'key': 'h',
    'which': 104,
    'altWhich': 1088,
    'code': 'KeyH',
  },
  'KeyG': {
    'key': 'g',
    'which': 103,
    'altWhich': 1087,
    'code': 'KeyG',
  },
  'KeyD': {
    'key': 'd',
    'which': 100,
    'altWhich': 1074,
    'code': 'KeyD',
  },
  'KeyS': {
    'key': 's',
    'which': 115,
    'altWhich': 1099,
    'code': 'KeyS',
  },
  'Backquote': {
    'key': '`',
    'which': 96,
    'altWhich': 1105,
    'shiftWhich': 126,
    'code': 'Backquote',
  },
  'Digit1': {
    'key': '1',
    'which': 49,
    'altWhich': 49,
    'shiftWhich': 33,
    'altShiftWhich': 33,
    'code': 'Digit1',
  },
  'Digit2': {
    'key': '2',
    'which': 50,
    'altWhich': 50,
    'shiftWhich': 64,
    'altShiftWhich': 34,
    'code': 'Digit2',
  },
  'Digit3': {
    'key': '3',
    'which': 51,
    'altWhich': 51,
    'shiftWhich': 35,
    'altShiftWhich': 8470,
    'code': 'Digit3',
  },
  'Digit4': {
    'key': '4',
    'which': 52,
    'altWhich': 52,
    'shiftWhich': 36,
    'altShiftWhich': 59,
    'code': 'Digit4',
  },
  'Digit5': {
    'key': '5',
    'which': 53,
    'altWhich': 53,
    'shiftWhich': 37,
    'altShiftWhich': 37,
    'code': 'Digit5',
  },
  'Digit6': {
    'key': '6',
    'which': 54,
    'altWhich': 54,
    'shiftWhich': 94,
    'altShiftWhich': 58,
    'code': 'Digit6',
  },
  'Digit7': {
    'key': '7',
    'which': 55,
    'altWhich': 55,
    'shiftWhich': 38,
    'altShiftWhich': 63,
    'code': 'Digit7',
  },
  'Digit8': {
    'key': '8',
    'which': 56,
    'altWhich': 56,
    'shiftWhich': 42,
    'altShiftWhich': 33,
    'code': 'Digit8',
  },
  'Digit9': {
    'key': '9',
    'which': 57,
    'altWhich': 57,
    'shiftWhich': 40,
    'altShiftWhich': 40,
    'code': 'Digit9',
  },
  'Digit0': {
    'key': '0',
    'which': 48,
    'altWhich': 48,
    'shiftWhich': 41,
    'altShiftWhich': 41,
    'code': 'Digit0',
  },
  'Minus': {
    'key': '-',
    'which': 45,
    'altWhich': 45,
    'shiftWhich': 95,
    'altShiftWhich': 95,
    'code': 'Minus',
  },
  'Equal': {
    'key': '=',
    'which': 61,
    'altWhich': 61,
    'shiftWhich': 43,
    'altShiftWhich': 43,
    'code': 'Equal',
  },
  'Backspace': {
    'key': 'Backspace',
    'which': 8,
    'code': 'Backspace',
  },
  'Tab': {
    'key': 'Tab',
    'which': 9,
    'code': 'Tab',
  },
  'KeyQ': {
    'key': 'q',
    'which': 113,
    'altWhich': 1081,
    'code': 'KeyQ',
  },
  'KeyW': {
    'key': 'w',
    'which': 119,
    'altWhich': 1094,
    'code': 'KeyW',
  },
  'KeyE': {
    'key': 'e',
    'which': 101,
    'altWhich': 1091,
    'code': 'KeyE',
  },
  'KeyR': {
    'key': 'r',
    'which': 114,
    'altWhich': 1082,
    'code': 'KeyR',
  },
  'KeyT': {
    'key': 't',
    'which': 116,
    'altWhich': 1077,
    'code': 'KeyT',
  },
  'KeyY': {
    'key': 'y',
    'which': 121,
    'altWhich': 1085,
    'code': 'KeyY',
  },
  'KeyU': {
    'key': 'u',
    'which': 117,
    'altWhich': 1075,
    'code': 'KeyU',
  },
  'KeyI': {
    'key': 'i',
    'which': 105,
    'altWhich': 1096,
    'code': 'KeyI',
  },
  'KeyO': {
    'key': 'o',
    'which': 111,
    'altWhich': 1097,
    'code': 'KeyO',
  },
  'KeyP': {
    'key': 'p',
    'which': 112,
    'altWhich': 1079,
    'code': 'KeyP',
  },
  'BracketLeft': {
    'key': '[',
    'which': 91,
    'shiftWhich': 123,
    'altWhich': 1093,
    'code': 'BracketLeft',
  },
  'BracketRight': {
    'key': ']',
    'which': 93,
    'shiftWhich': 125,
    'altWhich': 1098,
    'code': 'BracketRight',
  },
  'Backslash': {
    'key': '\\',
    'which': 92,
    'shiftWhich': 124,
    'code': 'Backslash',
  },
  'Delete': {
    'displayValue': 'Del',
    'which': 127,
    'code': 'Delete',
  },
  'CapsLock': {
    'displayValue': 'CapsLock',
    'which': 20,
    'code': 'CapsLock',
  },
  'KeyF': {
    'key': 'f',
    'which': 102,
    'altWhich': 1072,
    'code': 'KeyF',
  },
  'KeyA': {
    'key': 'a',
    'which': 97,
    'altWhich': 1092,
    'code': 'KeyA',
  },
};

